name: check-format
run-name: Running prettier check
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Check format
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main | xargs -n1)
          echo $CHANGED_FILES
          # FILES_TO_CHECK=$(echo $CHANGED_FILES | xargs -n1 | grep -E '\.ts$')

