name: check-format
run-name: Running prettier check
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
      # - name: Prettify code
        # uses: creyD/prettier_action@v4.3
        # with:
          # prettier_options: --check **/*.{ts}
          # only_changed: True
      # - run: npm install
      - run: |
          # Get files changed on this branch
          CHANGED_FILES=$(git diff --name-only origin/main)
          # Filter out non .ts files
          FILES_TO_CHECK=$(echo $CHANGED_FILES | xargs -n1 | grep -E '\.ts$')
          npm run format:check $FILES_TO_CHECK
          # Check changed .ts files if any found
          # if [ -n "$FILES_TO_CHECK" ]; then
            # echo $FILES_TO_CHECK
            # npm run format:check $FILES_TO_CHECK
          # else 
          # Exit with success if no .ts files have been changed
            # echo "No diffs found on this branch for .ts files."
            # exit 0
          # fi
