name: check-format
run-name: Running prettier check
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Check format
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main | xargs -n1 | grep -E '\.ts$')
          echo '------------'
          echo $CHANGED_FILES
          echo '------------'
          if [ "$CHANGED_FILES" ]; then
            echo "Found changes in .ts files - checking formatting"
            npm run format:check $CHANGED_FILES
          else
            echo "No changes found in .ts files"
            exit 0
          fi

