name: check-format
run-name: Running prettier check
on: [push]
jobs:
  check-file-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - run: npm install
      - run: |
          # Get files changed on this branch
          CHANGED_FILES=$(git diff --name-only origin/main)
          # Filter out non .ts files
          FILES_TO_CHECK=$(echo $CHANGED_FILES | xargs -n1 | grep -E '\.ts$')
          # Check changed .ts files
          npm run format:check $FILES_TO_CHECK
