name: check-format
run-name: Running prettier check
on: [push]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Check format
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check --no-error-on-unmatched-pattern **.*.{.ts}
          only_changed: True
